server:
  port: 8087

spring:
  application:
    name: pricingService

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: pricing-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.ridematching.common.*"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

pricing:
  base-fare: 50.0
  rate-per-km: 12.0
